spring:
  application:
    name: gestion-service
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc:mysql://mysql-db:3306/local_gestion_service?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      gestion-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
